### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by RobinChenRichmond** [craffel/simple_spearmint#8]
When trying to run setup.py install, the webpage could not be found.

Reading https://pypi.python.org/simple/spearmint/
Couldn't find index page for 'spearmint' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for spearmint

**Comment by craffel** [comment]
Sorry, how are you trying to install this?  Looks like a typo somewhere, simple/spearment instead of simple_spearmint ?
