### ISSUE TITLE
"Best parameters" are not the best, nor do they get updated

### ISSUE THREAD

**Issue by lzamparo** [craffel/simple_spearmint#9]
Hey,

Really loving this simplified interface to Spearmint, but I find that I'm having to manually parse the put of my job log files to actually find the best hyper-parameter configuration.  For example:

> GP trial 50: {'l1pool_size': 5, 'l2dropout': 0.46999540484424784, 'l1stride': 2, 'l2dense_size': 89, 'l1filter_size': 28, 'l1filters': 51} -> 0.8380936937224575
Best parameters {'l1pool_size': 4, 'l2dropout': 0.10733567157285298, 'l1stride': 2, 'l2dense_size': 75, 'l1filter_size': 7, 'l1filters': 89} for objective 0.5

The objective reports the maximum AUROC of a CNN on my problem, but ss seems to think my best parameters are in fact those of a failed random experiment (part of the warm-up to suggested experiments).  Do you observe this also?  And do you think this is a bug in the underlying Spearmint?

**Comment by lzamparo** [comment]
Woops, `best_parameters()` returns the configuration that achieves `np.nanargmin(self.objective_values)`.  Maybe the constructor could be modified to switch between reporting the min or max depending on the objective?  Or is the underlying Spearmint chooser also hard-coded to suggest parameters to minimize the objective?

**Comment by craffel** [comment]
>  Or is the underlying Spearmint chooser also hard-coded to suggest parameters to minimize the objective?

IIRC yes (please correct me if I'm wrong).  If you need to maximize, then you should minimize the negative objective.

> Maybe the constructor could be modified to switch between reporting the min or max depending on the objective?

I would think it would have to be user-specified, not depending on the objective (maybe that's what you mean).

**Comment by lzamparo** [comment]
Spearmint's [default_chooser.py](https://github.com/HIPS/Spearmint/blob/master/spearmint/choosers/default_chooser.py) suggests that the min is indeed returned:

```python
# find the min and argmin of the GP mean
current_best_location = grid[np.argmin(obj_mean),:][None]
best_ind = np.argmin(obj_mean)
current_best_value = obj_mean[best_ind]
std_at_best = np.sqrt(obj_var[best_ind])
```

> I would think it would have to be user-specified, not depending on the objective (maybe that's what you mean).

The former, yes.  I suggest adding a default arg to the constructor so that ss will take care of doing the conversion of maximizing the objective to minimizing the negative objective internally.  Should be pretty easy to do, mind if I submit a PR?

**Comment by lzamparo** [comment]
Alternatively, Spearmint could advertise more loudly that the objective needs to be written as a minimization problem always, and then it's on the user to ensure the problem is correctly set up.  I suspect I'm not the first person tempted by the glorious future of smart hyper-parameter optimization without noticing until after the fact that the best reported values are actually the worst.

**Comment by craffel** [comment]
I think either is fine; if you want to implement the correct logic feel free to do so.  I would think the cleanest approach would be a new argument in `SimpleSpearmint.__init__`.

**Comment by lzamparo** [comment]
Submitted a PR (#10) to address this
